type PixelSprite = string[]

const sprites = {
  star: [
    '......yy......',
    '......yy......',
    '.....yyyy.....',
    '.....yyyy.....',
    'yyyyyyyyyyyyyy',
    'yyyyyyyyyyyyyy',
    '..yyyyyyyyyy..',
    '..yyyyyyyyyy..',
    '...yyyyyyyy...',
    '...yyyyyyyy...',
    '..yyyyyyyyyy..',
    '..yyyyyyyyyy..',
    '..yyyy..yyyy..',
    '.yy........yy.',
  ],
  rocket: [
    '.....ww.....',
    '....wyyw....',
    '....wkkw....',
    '...wwyyww...',
    '...wkkkkw...',
    '...wkkkkw...',
    '...wyyyyw...',
    '..wyyyyyyw..',
    '.rrwyyyywrr.',
    '.rr.wyyw.rr.',
    '....rrrr....',
    '.....oo.....',
  ],
  smile: [
    '...yyyyyy...',
    '..yyyyyyyy..',
    '.yyyyyyyyyy.',
    'yyyyyyyyyyyy',
    'yykkyyyykkyy',
    'yykkyyyykkyy',
    'yyyyyyyyyyyy',
    'yykkkkkkkkyy',
    'yyykkkkkkyyy',
    '.yyyyyyyyyy.',
    '..yyyyyyyy..',
    '...yyyyyy...',
  ],
  heart: [
    '............',
    '..rr....rr..',
    '.rrrr..rrrr.',
    'rrrrrrrrrrrr',
    'rrrrrrrrrrrr',
    'rrrrrrrrrrrr',
    '.rrrrrrrrrr.',
    '..rrrrrrrr..',
    '...rrrrrr...',
    '....rrrr....',
    '.....rr.....',
    '............',
  ],
  ghost: [
    '....cccc....',
    '..cccccccc..',
    '.cccccccccc.',
    'cccccccccccc',
    'ccwwccccwwcc',
    'ccwkccccwkcc',
    'cccccccccccc',
    'cccccccccccc',
    'cccccccccccc',
    'cccccccccccc',
    'cccccccccccc',
    'c.cc.cc.cc.c',
  ],
  gamepad: [
    '............',
    '............',
    '.bbbbbbbbbb.',
    'bbbbbbbbbbbb',
    'bbwbbbbbbwbb',
    'bbwwwbbbywbb',
    'bbbbbbbyyybb',
    'bbbbbbbbbbbb',
    '.bbbbbbbbbb.',
    '............',
    '............',
    '............',
  ],
  cat: [
    'kk........kk',
    'kkk......kkk',
    '.kkkkkkkkkk.',
    'kkkkkkkkkkkk',
    'kkokkkkkokkk',
    'kkokkkkkokkk',
    'kkkkkkkkkkkk',
    'kkkookoookkk',
    '.kkkkkkkkkk.',
    '..kkkkkkkk..',
    '............',
    '............',
  ],
  mushroom: [
    '....rrrr....',
    '..rrwwrrrr..',
    '.rrwwrrwwrr.',
    'rrrrrwwrrrrr',
    'rrrrwwwwrrrr',
    'rrrrrrrrrrrr',
    '.rrrrrrrrrr.',
    '...wwwwww...',
    '...wwwwww...',
    '...wkkkkw...',
    '...wwwwww...',
    '............',
  ],
  hero: [
    '....rrrr....',
    '...rrrrrr...',
    '...nnwwnn...',
    '..nkwkkwkn..',
    '..nnnnnnnn..',
    '...nnnnnn...',
    '..bbbbbbbb..',
    '.bbbbbbbbbb.',
    'nnbwbbbbwbnn',
    '..bbbbbbbb..',
    '..rr....rr..',
    '.rrr....rrr.',
  ],
  wizard: [
    '.....mm.....',
    '....mmmm....',
    '...mmmmmm...',
    '..mmmmmmmm..',
    '.mmmmmmmmmm.',
    '...nnnnnn...',
    '..nkwkkwkn..',
    '..nnnnnnnn..',
    '..mmmmmmmm..',
    '.mmmmmmmmmm.',
    '..m......m..',
    '............',
  ],
  ninja: [
    '............',
    '..kkkkkkkk..',
    '.kkkkkkkkkk.',
    '.kkwkkkkwkk.',
    '.kkkkkkkkkk.',
    '..kkkkkkkk..',
    '..rrrrrrrr..',
    '.rrkrrrrkrr.',
    '..rrrrrrrr..',
    '..kk....kk..',
    '.kkk....kkk.',
    '............',
  ],
  knight: [
    '....dddd....',
    '...dddddd...',
    '..dddddddd..',
    '..dwddddwd..',
    '..dddddddd..',
    '...dddddd...',
    '.rrrrrrrrrr.',
    'rrrddddddrrr',
    'rr.dddddd.rr',
    '...dddddd...',
    '...rr..rr...',
    '..rrr..rrr..',
  ],
  robot: [
    '.....cc.....',
    '.....cc.....',
    '..dddddddd..',
    '.dddddddddd.',
    '.ddwwddwwdd.',
    '.dddddddddd.',
    '.dddbbbbddd.',
    '..dddddddd..',
    '.c.dddddd.c.',
    'cccddddddccc',
    '...dd..dd...',
    '..ddd..ddd..',
  ],
  slime: [
    '............',
    '............',
    '....gggg....',
    '..gggggggg..',
    '.gggggggggg.',
    'ggkgggggkggg',
    'ggkgggggkggg',
    'gggggggggggg',
    'gggggggggggg',
    '.gggggggggg.',
    '..gggggggg..',
    '...gggggg...',
  ],
  invader: [
    '............',
    '....gggg....',
    '...gggggg...',
    '..gggggggg..',
    '.gg.gggg.gg.',
    'gggggggggggg',
    'g.gggggggg.g',
    'g.g......g.g',
    '...gg..gg...',
    '..gg.gg.gg..',
    '............',
    '............',
  ],
  fighter: [
    '.....cc.....',
    '....cccc....',
    '....cccc....',
    '.cccccccccc.',
    'cccccccccccc',
    'ccwwwwwwwwcc',
    'cccccccccccc',
    '.cccccccccc.',
    '...cc..cc...',
    '..cc....cc..',
    '.c........c.',
    '............',
  ],
  sword: [
    '.....dd.....',
    '.....dw.....',
    '.....dw.....',
    '.....dw.....',
    '.....dw.....',
    '.....dw.....',
    '.....dw.....',
    '..yyyrryyy..',
    '.....oo.....',
    '.....oo.....',
    '.....yy.....',
    '............',
  ],
  shield: [
    '.dddddddddd.',
    '.dbbbbbbbbd.',
    '.dbbbyybbbd.',
    '.dyyyyyyyyd.',
    '.dbbbyybbbd.',
    '.dbbbyybbbd.',
    '..dbbyybbd..',
    '..dbbyybbd..',
    '...dbyybd...',
    '....dyyd....',
    '.....dd.....',
    '............',
  ],
  potion: [
    '.....yy.....',
    '.....yy.....',
    '....wwww....',
    '...wwwwww...',
    '..wwwwwwww..',
    '..wrrrrrrw..',
    '..wrrrrrrw..',
    '..wrrrrrrw..',
    '..wrrrrrrw..',
    '..wwwwwwww..',
    '............',
    '............',
  ],
  bomb: [
    '.........oo.',
    '........yy..',
    '.......yy...',
    '....kkkk....',
    '..kkkkkkkk..',
    '.kkkwwkkkkk.',
    '.kkwwkkkkkk.',
    '.kkkkkkkkkk.',
    '.kkkkkkkkkk.',
    '..kkkkkkkk..',
    '...kkkkkk...',
    '....kkkk....',
  ],
} satisfies Record<string, PixelSprite>

export type PixelIconName = keyof typeof sprites

const palette: Record<string, string> = {
  y: 'var(--gold)',
  r: 'var(--red)',
  b: 'var(--blue)',
  c: '#3cbcfc',
  g: 'var(--green)',
  k: '#1a1c2c',
  n: '#f8b878',
  m: '#6844fc',
  d: '#b8b8b8',
  w: '#fffbe8',
  o: '#f87858',
}

type PixelIconProps = {
  name: PixelIconName
}

export function PixelIcon({ name }: PixelIconProps) {
  const sprite = sprites[name]

  return (
    <svg
      viewBox={`0 0 ${sprite[0].length} ${sprite.length}`}
      fill="none"
      shapeRendering="crispEdges"
      aria-hidden="true"
    >
      {sprite.flatMap((row, y) =>
        row.split('').map((pixel, x) =>
          pixel === '.' ? null : (
            <rect key={`${x}-${y}`} x={x} y={y} width={1} height={1} fill={palette[pixel]} />
          ),
        ),
      )}
    </svg>
  )
}
